services:
  torch:
    build:
      context: .
      dockerfile: ./docker/torch/Dockerfile
      args:
        # [format] pytorch/pytorch:${PYTORCH_VERSION}-cuda${PYTORCH_CUDA_VERSION}-cudnn${PYTORCH_CUDNN_VERSION}-devel
        # See https://hub.docker.com/r/pytorch/pytorch/tags?page=1&name=devel
        # - PYTORCH_VERSION=1.11.0
        # - PYTORCH_CUDA_VERSION=11.3
        # - PYTORCH_CUDNN_VERSION=8
        # User ID. for acounts with UID!=1000
        - UID=${USERID:-1000}
        # - USERNAME=torchuser

    volumes:
      - .:/usr/src
    shm_size: '8gb'
    working_dir: /usr/src

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
