defaults:
  - _self_

config:
  experiment:
    # experiment name
    name: experiment
    # folder for saving checkpoint
    ckpt_folder: checkpoint
    # filename for logging
    log_file: log.log
    # logging interval
    log_interval: 100
    # file to output execution status. If null, ignored.
    exec_status_output: ./execstatus.txt

  data:
    # dataset root folder
    data_root: ./data
    # size of image
    image_size: 128

    # arguments for DataLoader
    loader:
      shuffle: true
      drop_last: true
      num_workers: 4
      batch_size: 32
      pin_memory: true

    # transforms
    transforms:
      - name: RandomHorizontalFlip
        p: 0.5
      - name: Resize
        size: ${config.data.image_size}
      - name: CenterCrop
        size: ${config.data.image_size}
      - name: ToTensor
      - name: Normalize
        mean: 0.5
        std: 0.5

  model:
    # arguments for generator
    generator:
      name: model.model.Generator
      params:
        latent_dim: 128
        base_channels: 64
    # arguments for discriminator
    discriminator:
      name: model.model.Discriminator
      params:
        base_channels: 64

  train:
    # epochs to train (selectively use iterations)
    epochs: 100
    # iterations to train (selectively use epochs)
    iterations: -1

    # number of samples for eval
    test_sample: 16

    optimizer:
      # optimizer for generator
      generator:
        name: torch.optim.Adam
        params:
          lr: 0.0002
          betas: [0.5, 0.999]
      # optimizer for discriminator
      discriminator:
        name: torch.optim.Adam
        params:
          lr: 0.0002
          betas: [0.5, 0.999]

    # use EMA?
    ema: false
    # decay for EMA update
    ema_decay: 0.999

    # policy for DiffAugment
    diffaugment_policy: null

    # save mode every
    save: 1000

  env:
    # device. 'cpu' or 'cuda' or 'cuda:{0,1,2...}'
    device: cuda
    # Use half precision?
    amp: false
    # Use deterministic algorithm?
    use_deterministic: false
